### ISSUE TITLE
Word Break inconsistency between Chrome and Firefox

### ISSUE THREAD

**Issue by ghost** [ikrishg/reseter.css#19]
**Is your feature request related to a problem? Please describe.**
Chrome doesn't wrap its links at all while Firefox does.
Chrome uses a different default value for word-break then Firefox as after adding word-break: break-word; on its links it behaved the same way as Firefox did.
I also saw that similar questions have come up before and they were put aside because of "unexpected behaviors", but this seems like a special case as it to only happens with the <a> tag so it could be an exception.

**Describe the solution you'd like**
```css
a {
  cursor: pointer;
  color: #3333e1;
  background-color: transparent;
  text-decoration: none;
  word-break: normal;
}
```

**Additional context**
Originally Opened By @Gaboris at necolas/normalize.css#851 Plus, Original Solution By @VixieTSQ in necolas/normalize.css#852
